#+title: Tomahawk56 ZMK Keymap
#+PROPERTY: header-args:c :comments no :padline no

This file is the literate source for =tomahawk56.keymap=.

To regenerate the keymap from this document, run =org-babel-tangle= from Emacs while visiting this file.

This file is also configured to tangle automatically on save via a file-local Emacs hook.

*WARNING*: ZMK layers are indexed by their *position* in the keymap block, NOT by
the =#define= value. The =#define= numbers in the =includes-and-defines= block MUST
match the order that layers appear in the keymap. If you reorder layers or add/remove
layers, you MUST update the =#define= values to match. Getting this wrong will cause
layers to point to the wrong places, and you may lose access to the Admin/bootloader
layer — requiring a physical reset button double-tap to recover.


* Tangled Output

#+begin_src c :tangle tomahawk56.keymap :noweb yes
<<license>>
<<includes-and-defines>>
<<optional-hardware>>
<<led-strip>>
<<root>>
#+end_src

* Header

#+name: license
#+begin_src c
/*
 * Copyright (c) 2020 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */
#+end_src

#+name: includes-and-defines
#+begin_src c
#include <behaviors.dtsi>
#include <dt-bindings/zmk/bt.h>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/rgb.h>
#include <dt-bindings/zmk/backlight.h>

#define BASE 0
#define NUMBERS 1
#define SYMBOL_1 2
#define SYMBOL_2 3
#define AOE4 4
#define AOE4_FN 5
#define ADMIN 6
#+end_src

* Hardware Notes

#+name: optional-hardware
#+begin_src c
/*
 * Assign the cs-gpios pin to 4.
 * Uncomment these next few lines if implementing nice!view Displays
 */

// nice_view_spi: &spi0 { cs-gpios = <&pro_micro 4 GPIO_ACTIVE_HIGH>; };
#+end_src

#+name: led-strip
#+begin_src c
// Uncomment this block if using RGB
&led_strip {
    chain-length = <28>;
};
#+end_src


* Keymap

#+name: root
#+begin_src c :noweb yes
/ {
    behaviors {
<<hm-behavior>>

<<tg-behavior>>

<<td-aoe4-behavior>>
    };

    keymap {
        compatible = "zmk,keymap";

<<default-layer>>

<<numbers-layer>>

<<symbol-1-layer>>

<<symbol-2-layer>>

<<aoe4-layer>>
    
<<aoe4-fn-layer>>

<<admin-layer>>

        extra_3 { status = "reserved"; };
    };
};
#+end_src

** Behaviors

#+name: hm-behavior
#+begin_src c
        hm: homerow_mods {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            tapping-term-ms = <200>;
            quick-tap-ms = <50>;
            flavor = "tap-preferred";
            bindings = <&kp>, <&kp>;
        };
#+end_src

#+name: tg-behavior
#+begin_src c
        tg: tab_game_toggle {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            tapping-term-ms = <200>;
            quick-tap-ms = <50>;
            flavor = "tap-preferred";
            bindings = <&kp>, <&tog>;
        };
#+end_src

#+name: td-aoe4-behavior
#+begin_src c
        td_aoe4: tap_dance_aoe4 {
            compatible = "zmk,behavior-tap-dance";
            #binding-cells = <0>;
            tapping-term-ms = <300>;
            bindings = <&none>, <&tog AOE4>;
        };
#+end_src

** Base

Main matrix:

| ESC    | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 | BSPC    |
| TAB    | Q | W | E | R | T | Y | U | I | O | P | -/AD    |
| CAPS   | A | S | D | F | G | H | J | K | L | ; | '       |
| SHIFT  | Z | X | C | V | B | N | M | , | . | / | 2xAOE   |

Thumbs:

| HYPER | TAB/ME | SPACE | ESC/# | ESC/S1 | ENTER | BSP/S2 | CMD |

#+name: default-layer
#+begin_src c
        default_layer {
            display-name = "Base";
            bindings = <
&kp ESC         &kp N1  &kp N2            &kp N3            &kp N4  &kp N5               &kp N6  &kp N7  &kp N8             &kp N9          &kp N0    &kp BSPC
&kp TAB         &kp Q   &kp W             &kp E             &kp R   &kp T                &kp Y   &kp U   &kp I              &kp O           &kp P     &lt ADMIN MINUS
&kp CAPSLOCK    &hm LGUI A  &hm LALT S    &hm LCTRL D       &hm LSHFT F  &kp G           &kp H   &hm RSHFT J  &hm RCTRL K      &hm LALT L      &hm RGUI SEMI  &kp SQT
&kp LEFT_SHIFT  &kp Z   &kp X             &kp C             &kp V   &kp B                &kp N   &kp M   &kp COMMA          &kp DOT         &kp FSLH  &td_aoe4
                        &kp LC(LS(LA(LGUI)))  &mt LC(LA(LSHFT)) TAB  &kp SPACE &lt NUMBERS ESC  &lt SYMBOL_1 ESC &kp RET &lt SYMBOL_2 BSPC &kp RIGHT_COMMAND
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src

** Numbers

Main matrix:

|   |      |   |   |   |     |   | 7 | 8 | 9 | = |   |
|   | BACK |   |   |   | FWD | \ | 4 | 5 | 6 | 0 |   |
|   |      |   |   |   |     | ` | 1 | 2 | 3 | / |   |

Thumbs:

| TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS |

#+name: numbers-layer
#+begin_src c
        numbers_layer {
            display-name = "Numbers";
            bindings = <
&trans     &trans    &trans    &trans     &trans  &trans            &trans       &trans     &trans     &trans    &trans    &trans
&trans     &none     &none     &none      &none   &none             &kp MINUS    &kp N7     &kp N8     &kp N9    &kp EQUAL &trans
&trans     &kp K_BACK &none    &none      &none   &kp K_FORWARD     &kp BSLH     &kp N4     &kp N5     &kp N6    &kp N0    &trans
&trans     &none     &none     &none      &none   &none             &kp GRAVE    &kp N1     &kp N2     &kp N3    &kp FSLH  &trans
                     &trans    &trans     &trans  &trans            &trans       &trans     &trans     &trans
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src

** Symbol 1

Main matrix:

|   | [ | ( | ) | ] | ? |      | VOL- | VOL+ | MUTE  |   |   |
|   | ^ | = | _ | $ | * | LEFT | DOWN | UP   | RIGHT |   |   |
|   | ! | [ | ] | - | / |      |      |      |       |   |   |

Thumbs:

| TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS |

#+name: symbol-1-layer
#+begin_src c
        symbol_1_layer {
            display-name = "Symbol 1";
            bindings = <
&trans     &trans     &trans     &trans      &trans     &trans            &trans     &trans        &trans        &trans      &trans    &trans
&trans     &kp LBRC   &kp LPAR   &kp RPAR    &kp RBRC   &kp QMARK         &none      &kp K_VOL_DN  &kp K_VOL_UP  &kp K_MUTE  &none     &trans
&trans     &kp CARET  &kp EQUAL  &kp UNDER   &kp DLLR   &kp STAR          &kp LEFT   &kp DOWN      &kp UP        &kp RIGHT   &none     &trans
&trans     &kp EXCL   &kp LBKT   &kp RBKT    &kp MINUS  &kp FSLH          &none      &none         &none         &none       &none     &trans
                      &trans      &trans      &trans     &trans            &trans     &trans        &trans        &trans
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src

** Symbol 2

Main matrix:

|   | # | : | ; | ' | " |    |   |   |   |   |   |   |
|   | ~ | < | > |   |   | \\ |   |   |   |   |   |   |
|   | @ | & | % | + | . |    |   |   |   |   |   |   |

Thumbs:

| TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS |

#+name: symbol-2-layer
#+begin_src c
        symbol_2_layer {
            display-name = "Symbol 2";
            bindings = <
&trans     &trans      &trans      &trans     &trans     &trans          &trans      &trans      &trans      &trans      &trans      &trans
&trans     &kp HASH    &kp COLON   &kp SEMI   &kp SQT    &kp DQT         &none       &none       &none       &none       &none       &trans
&trans     &kp TILDE   &kp LT      &kp GT     &kp PIPE   &kp BSLH        &none       &none       &none       &none       &none       &trans
&trans     &kp AT      &kp AMPS    &kp PRCNT  &kp PLUS   &kp DOT         &none       &none       &none       &none       &none       &trans
                       &trans       &trans     &trans     &trans          &trans      &trans      &trans      &trans
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src

** AOE4

*** Base

Main matrix:

| ESC    | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 | BSPC   |
| ALT    | Q | W | E | R | T | Y | U | I | O | P |        |
| DEL/FN | A | S | D | F | G | H | J | K | L | ; | '      |
| TAB    | Z | X | C | V | B | N | M | , | . | / | 2xAOE  |

Thumbs:

| SPACE | CTRL | SHIFT | H | ESC | ENTER | BSPC | CTRL |

#+name: aoe4-layer
#+begin_src c
        aoe4_layer {
            display-name = "AOE4";
            bindings = <
&kp ESC         &kp N1  &kp N2  &kp N3  &kp N4  &kp N5            &kp N6  &kp N7  &kp N8     &kp N9    &kp N0    &kp BSPC
&kp LALT        &kp Q   &kp W   &kp E   &kp R   &kp T             &kp Y   &kp U   &kp I      &kp O     &kp P     &none
&lt AOE4_FN DEL  &kp A   &kp S   &kp D   &kp F   &kp G             &kp H   &kp J   &kp K      &kp L     &kp SEMI  &kp SQT
&kp TAB         &kp Z   &kp X   &kp C   &kp V   &kp B             &kp N   &kp M   &kp COMMA  &kp DOT   &kp FSLH  &td_aoe4
                        &kp SPACE  &kp LCTRL  &kp LSHFT  &kp H  &kp ESC  &kp RET  &kp BSPC  &kp RCTRL
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src

*** AOE4 FN

Main matrix:

|   |  6  |  7   |  8 |  9 |  0 |   |   |   |   |   |   |
|   | F1  | F2   | F3 | F4 | F5 |   |   |   |   |   |   |
|   |     | HOME |  , |  . |    |   |   |   |   |   |   |
|   |     |      |    |    |    |   |   |   |   |   |   |

Thumbs:

| TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS |

#+name: aoe4-fn-layer
#+begin_src c
        aoe4_fn_layer {
            display-name = "AOE4 FN";
            bindings = <
&trans         &kp N6   &kp N7   &kp N8   &kp N9   &kp N0           &trans  &trans  &trans    &trans   &trans   &trans
&trans         &kp F1   &kp F2   &kp F3   &kp F4   &kp F5           &trans  &trans  &trans    &trans   &trans   &trans
&trans         &none    &kp HOME &kp COMMA &kp DOT &trans           &trans  &trans  &trans    &trans   &trans   &trans
&trans         &trans   &trans   &trans   &trans   &trans           &trans  &trans  &trans    &trans   &trans   &trans
                        &trans    &trans    &trans            &trans      &trans   &trans   &trans    &trans
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src

** Admin

Main matrix:

| BTCLR | BT1 | BT2 | BT3 | BT4 | BT5 | RGB  | HUE+ | SAT+ | BRI+ | SPD+ | FX+ |
|       |     |     |     |     |     |      | HUE- | SAT- | BRI- | SPD- | FX- |
| `     | !   | @   | #   | $   | %   | ^    | &    | *    | (    | )    | ~   |
| BOOT  |     |     |     | [   | ]   | BOOT | _    | +    | {    | }    | |   |

Thumbs:

| TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS | TRANS |

#+name: admin-layer
#+begin_src c
        admin_layer {
            display-name = "Admin";
            bindings = <
&bt BT_CLR  &bt BT_SEL 0  &bt BT_SEL 1  &bt BT_SEL 2  &bt BT_SEL 3  &bt BT_SEL 4         &rgb_ug RGB_TOG  &rgb_ug RGB_HUI  &rgb_ug RGB_SAI  &rgb_ug RGB_BRI  &rgb_ug RGB_SPI  &rgb_ug RGB_EFF
&trans      &trans        &trans        &trans        &trans        &trans               &trans           &rgb_ug RGB_HUD  &rgb_ug RGB_SAD  &rgb_ug RGB_BRD  &rgb_ug RGB_SPD  &rgb_ug RGB_EFR
&kp GRAVE   &kp EXCL      &kp AT        &kp HASH      &kp DOLLAR    &kp PRCNT            &kp CARET  &kp AMPS   &kp KP_MULTIPLY  &kp LPAR  &kp RPAR  &kp TILDE
&bootloader &trans        &trans        &trans        &kp LBKT      &kp RBKT             &bootloader &kp MINUS  &kp KP_PLUS      &kp LBRC  &kp RBRC  &kp PIPE
                          &trans        &trans        &trans        &trans               &trans  &trans     &trans     &trans
            >;

            sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
        };
#+end_src


* Footer
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda () (when (derived-mode-p 'org-mode) (org-babel-tangle))) nil t)
# End:
